(function(){
"use strict";
const A=VDMApp,D=A.read("social",{}),root=document.getElementById("app-body"),viewer=D.viewer||{id:"local-viewer",name:"You",handle:"local"};A.frame(A.brand.name,A.brand.description);document.querySelector(".app-mark").textContent=A.brand.icon||"";
const S=A.appState({view:"home",likes:[],reposts:[],bookmarks:[],following:[],posts:[],query:"",detail:null,profileUserId:null,previousView:"home"});
const accounts=()=>[viewer,...(D.accounts||[])];const allPosts=()=>[...S.posts,...(D.posts||[])];const account=id=>accounts().find(a=>a.id===id)||{id,status:"missing",name:"Unknown",handle:"unknown"};const visible=p=>!p.availableWhen||A.state.hasEvidence(p.availableWhen);
function save(){A.saveAppState(S);}function setView(v,arg){S.view=v;S.detail=arg||null;if(v!=="profile-other")S.profileUserId=null;save();render();}
function nav(){return ["home","following","explore","notifications","bookmarks","profile"].map(v=>'<button class="nav-button" data-view="'+v+'" aria-current="'+(S.view===v?'page':'false')+'">'+({home:"ホーム",following:"フォロー中",explore:"話題を検索",notifications:"通知",bookmarks:"ブックマーク",profile:"プロフィール"}[v])+'</button>').join('');}
function postCard(p){if(p.status==="deleted")return '<article class="deleted-post">この投稿は削除されました'+(p.remnant?'<p>'+A.esc(p.remnant)+'</p>':'')+'</article>';const u=account(p.authorId),media=p.media?'<button class="nav-button" data-media="'+p.id+'"><img class="post-media" src="'+A.esc(p.media.src)+'" alt="'+A.esc(p.media.alt||'')+'"></button><details><summary>画像の説明</summary>'+A.esc(p.media.alt||'説明はありません')+'</details>':'';const quote=p.quoteId?'<blockquote>'+A.esc(allPosts().find(x=>x.id===p.quoteId)?.text||'削除された引用投稿')+'</blockquote>':'';return '<article class="post" data-post="'+p.id+'"><div class="post-meta"><span class="avatar">'+A.esc((u.name||'?').slice(0,1))+'</span><button class="nav-button" data-profile="'+u.id+'"><strong>'+A.esc(u.name)+'</strong> @'+A.esc(u.handle)+'</button></div><p>'+A.esc(p.text||'')+'</p>'+quote+media+'<div class="post-actions"><button data-act="reply">返信</button><button data-act="quote">引用</button><button data-act="repost" class="'+(S.reposts.includes(p.id)?'on':'')+'">再共有</button><button data-act="like" class="'+(S.likes.includes(p.id)?'on':'')+'">いいね</button><button data-act="save" class="'+(S.bookmarks.includes(p.id)?'on':'')+'">保存</button><button data-act="detail">詳細</button></div></article>';}
function selectPosts(){let posts=allPosts().filter(visible);if(S.view==="following")posts=posts.filter(p=>S.following.includes(p.authorId)||p.authorId===viewer.id);if(S.view==="bookmarks")posts=posts.filter(p=>S.bookmarks.includes(p.id));if(S.view==="profile")posts=posts.filter(p=>p.authorId===viewer.id);if(S.view==="explore"&&S.query)posts=posts.filter(p=>VDMText.includesAll([p.text,account(p.authorId).name,account(p.authorId).handle].join(' '),S.query));if(S.detail)posts=posts.filter(p=>p.id===S.detail||p.replyTo===S.detail);return posts;}
function compose(replyTo,quoteId){return '<form class="compose" data-compose><textarea class="field" name="text" maxlength="500" placeholder="'+(replyTo?'返信を書く':'いまどうしてる？')+'"></textarea><input type="hidden" name="replyTo" value="'+A.esc(replyTo||'')+'"><input type="hidden" name="quoteId" value="'+A.esc(quoteId||'')+'"><div class="toolbar"><button class="primary">投稿する</button><span class="muted">端末内だけに保存されます</span></div></form>';}
function profileHead(id){const u=account(id||viewer.id),status=u.status||"public",followed=S.following.includes(u.id),labels={public:"公開",private:"非公開",suspended:"停止中",deleted:"削除済み",missing:"見つかりません"};return '<div class="profile-hero"></div><div class="profile-card"><span class="avatar">'+A.esc((u.name||"?").slice(0,1))+'</span><h2>'+A.esc(u.name)+'</h2><p>@'+A.esc(u.handle)+'</p><span class="pill">'+A.esc(labels[status]||status)+'</span><p>'+A.esc(u.bio||"")+'</p>'+(u.id!==viewer.id&&status==="public"?'<button class="primary" data-follow="'+u.id+'">'+(followed?'フォロー中':'フォロー')+'</button>':'')+(status==="private"?'<p class="muted">このアカウントの投稿は非公開です。</p>':status!=="public"?'<p class="muted">このプロフィールの投稿は表示できません。</p>':'')+'</div>';}
function render(){let center='';if(S.view==="profile-other"){const u=account(S.profileUserId),canShow=(u.status||"public")==="public";center='<header class="social-head"><button class="ghost" data-profile-back>← 戻る</button><h2>プロフィール</h2></header>'+profileHead(u.id)+(canShow?allPosts().filter(p=>p.authorId===u.id).map(postCard).join(""):"");}else if(S.view==="notifications")center='<header class="social-head"><h2>通知</h2></header>'+((D.notifications||[]).map(n=>'<article class="post"><strong>'+A.esc(n.title)+'</strong><p>'+A.esc(n.text)+'</p></article>').join('')||'<div class="empty">新しい通知はありません</div>');else{const detail=S.detail&&allPosts().find(p=>p.id===S.detail);center='<header class="social-head"><h2>'+(detail?'スレッド':({home:'ホーム',following:'フォロー中',explore:'話題を検索',bookmarks:'ブックマーク',profile:'プロフィール'}[S.view]||'Social'))+'</h2></header>'+(S.view==='profile'?profileHead(viewer.id):'')+(S.view==='explore'?'<form class="compose" data-search><input class="field" name="q" value="'+A.esc(S.query)+'" placeholder="投稿またはアカウントを検索"></form>':S.view==='home'?compose():'')+(detail?postCard(detail)+compose(detail.id):'')+selectPosts().filter(p=>!detail||p.id!==detail.id).map(postCard).join('');}
root.innerHTML='<section class="social-layout"><nav class="social-nav">'+nav()+'<button class="primary" data-compose-open>投稿</button></nav><main class="social-feed">'+center+'</main><aside class="social-aside"><h3>いま話題</h3>'+(D.trends||[]).map(t=>'<button class="nav-button" data-trend="'+A.esc(t)+'">'+A.esc(t)+'</button>').join('')+'<h3>おすすめ</h3>'+(D.accounts||[]).slice(0,4).map(u=>'<button class="nav-button" data-profile="'+u.id+'">@'+A.esc(u.handle)+'</button>').join('')+'</aside></section>';bind();}
function toggle(list,id){const i=list.indexOf(id);i<0?list.push(id):list.splice(i,1);save();render();}
function bind(){root.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));root.querySelector('[data-compose-open]')?.addEventListener('click',()=>{setView('home');setTimeout(()=>root.querySelector('textarea')?.focus(),0);});root.querySelectorAll('[data-profile]').forEach(b=>b.onclick=()=>{if(S.view!=="profile-other")S.previousView=S.view;S.view="profile-other";S.detail=null;S.profileUserId=b.dataset.profile;save();render();});root.querySelector('[data-profile-back]')?.addEventListener('click',()=>setView(S.previousView||"home"));root.querySelectorAll('[data-follow]').forEach(b=>b.onclick=()=>toggle(S.following,b.dataset.follow));root.querySelectorAll('[data-post]').forEach(el=>el.querySelectorAll('[data-act]').forEach(b=>b.onclick=()=>{const id=el.dataset.post,a=b.dataset.act;if(a==='like')toggle(S.likes,id);else if(a==='save')toggle(S.bookmarks,id);else if(a==='repost')toggle(S.reposts,id);else if(a==='detail')setView('detail',id);else{setView('detail',id);setTimeout(()=>{const f=root.querySelector('[data-compose]');if(f){f.querySelector('[name='+ (a==='quote'?'quoteId':'replyTo') +']').value=id;f.querySelector('textarea').focus();}},0);}}));root.querySelectorAll('[data-media]').forEach(b=>b.onclick=()=>{const p=allPosts().find(x=>x.id===b.dataset.media);VDMMedia.open(Object.assign({type:'image'},p.media));VDMEvidence.observe(p,'open-media');});root.querySelector('[data-compose]')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),text=String(f.get('text')||'').trim();if(!text)return;S.posts.unshift({id:'local-'+Date.now(),authorId:viewer.id,text,replyTo:f.get('replyTo')||null,quoteId:f.get('quoteId')||null,createdAt:new Date().toISOString(),status:'published'});save();render();});root.querySelector('[data-search]')?.addEventListener('submit',e=>{e.preventDefault();S.query=new FormData(e.currentTarget).get('q')||'';save();render();});root.querySelectorAll('[data-trend]').forEach(b=>b.onclick=()=>{S.query=b.dataset.trend;setView('explore');});}
render();
})();


